version: '3'

# NOTICE! Before app starting you need to create '.bot-env' file with BOT_TOKEN and ADMIN_ID

services:
  postgres_db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: dilikat
      POSTGRES_PASSWORD: dilikat
      POSTGRES_DB: dilikat
    ports:
      - '5432:5432'
    volumes:
      - postgres_db_data:/var/lib/postgresql/data/

  bot:
    build: ./
    container_name: bot
    restart: always
    depends_on:
      - postgres_db
    environment:
      # BOT_TOKEN and ADMIN_ID located in '.bot-env' file
      POSTGRES_DB: dilikat
      POSTGRES_USER: dilikat
      POSTGRES_PASSWORD: dilikat
      POSTGRES_HOST: postgres_db
      POSTGRES_PORT: 5432

volumes:
  postgres_db_data:
